version: "3"

services:

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: testapi_db
    ports:
      - 27017:27017
  app:
    build: .
    depends_on: 
      - mongodb
    ports:
      - 8080:8080
    environment:
      MONGO_URI: mongodb://root:root@mongodb:27017/    

  